-- liquibase formatted sql

-- changeset rober:1748513216910-1
CREATE TABLE customer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    phone       VARCHAR(255),
    customer_id VARCHAR(255)                            NOT NULL,
    PRIMARY KEY (id)
);
